import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";

import '@/styles/globals.scss'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ambélé, On Est Ensemble</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* // TODO: NAVBAR */}
      <Navbar />

      <Component {...pageProps} />
    </>
  );
}
